### ISSUE TITLE
Doesn't build with Go 1.10

### ISSUE THREAD

**Issue by aeryncaen** [dradtke/packer-builder-vultr#2]
```
 # github.com/hashicorp/packer/builder/vultr
builder/vultr/builder.go:150:28: cannot use *communicator.StepConnect literal (type *communicator.StepConnect) as type "github.com/mitchellh/multistep".Step in array or slice literal:
        *communicator.StepConnect does not implement "github.com/mitchellh/multistep".Step (wrong type for Cleanup method)
                have Cleanup("github.com/hashicorp/packer/helper/multistep".StateBag)
                want Cleanup("github.com/mitchellh/multistep".StateBag)
builder/vultr/builder.go:152:8: cannot use commHost (type func("github.com/mitchellh/multistep".StateBag) (string, error)) as type func("github.com/hashicorp/packer/helper/multistep".StateBag) (string, error) in field value
builder/vultr/builder.go:153:13: cannot use sshConfig (type func("github.com/mitchellh/multistep".StateBag) (*ssh.ClientConfig, error)) as type func("github.com/hashicorp/packer/helper/multistep".StateBag) (*ssh.ClientConfig, error) in field value
builder/vultr/builder.go:155:24: cannot use common.StepProvision literal (type *common.StepProvision) as type "github.com/mitchellh/multistep".Step in array or slice literal:
        *common.StepProvision does not implement "github.com/mitchellh/multistep".Step (wrong type for Cleanup method)
                have Cleanup("github.com/hashicorp/packer/helper/multistep".StateBag)
                want Cleanup("github.com/mitchellh/multistep".StateBag)
```

**Comment by dradtke** [comment]
This should be fixed now.
